---
title: "Talks and Publications"
draft: false
layout: "post"
url: "/publications/"
canonicalURL: "https://www.riccardocappuzzo.com/publications"
summary: The list of publications I have worked on.
listing: false
hidden_from_index: true
---

## Talks
* **Timeseries forecasting with skrub Data Ops**: EuroScipy 2025, with Guillaume Lemaitre
    * [Website](https://skrub-data.org/EuroSciPy2025/intro.html)
    * [Video recording](https://www.youtube.com/watch?v=hbmfiBX5zZc)
* **Skrub -- Machine learning with dataframes**: PyData Paris 2025
    * [Slides](https://skrub-data.org/skrub-materials/pages/slides/pydata-2025/slides.html)
    * [Video recording](https://www.youtube.com/watch?v=k9MNMDpgdAk)
* **Skrub tutorials material**: To be presented
    * [Website](https://skrub-data.org/skrub-tutorials/)

## Publications

* Riccardo Cappuzzo, Gael Varoquaux, Aimee Coelho, Paolo Papotti: **Retrieve, Merge, Predict: Augmenting Tables with Data Lakes** TMLR2025, [PDF](/static/pubs/arxiv-retrieve_merge_predict.pdf)

* Riccardo Cappuzzo, Paolo Papotti, and Saravanan Thirumuruganathan: **Relational Data Imputation with Graph Neural Networks** EDBT2024, [PDF](/static/pubs/hal-grimp-edbt.pdf)

* Riccardo Cappuzzo, Paolo Papotti, and Saravanan Thirumuruganathan: **Creating Embeddings of Heterogeneous Relational Datasets for Data Integration Tasks.** SIGMOD 2020,  [PDF](/static/pubs/sigmod-2020-embdi.pdf)

* Riccardo Cappuzzo, Paolo Papotti, Saravanan Thirumuruganathan:
**EmbDI: Generating Embeddings for Relational Data Integration (Discussion Paper).** SEBD 2021 [PDF](/static/pubs/embdi-sebd-2021.pdf)

* Riccardo Cappuzzo, under the supervision of Paolo Papotti, Elena Baralis: **Clustering of Categorical Data for Anonymization and Anomaly Detection**.
Master Thesis at Politecnico di Torino [PDF](/static/pubs/master-thesis-polito.pdf)

* Riccardo Cappuzzo, under the supervision of Paolo Papotti:
**Deep Learning Models for Tabular Data Curation**.
PhD Thesis at EURECOM/Sorbonne University [PDF](/static/pubs/phd-thesis-cappuzzo.pdf)
